### ISSUE TITLE
Local模式下，提交Job报错

### ISSUE THREAD

**Issue by MVCQ** [hairless/plink#178]
Cluster.mode：local

java.lang.NullPointerException: null
        at org.apache.flink.util.Preconditions.checkNotNull(Preconditions.java:61)
        at org.apache.flink.client.program.PackagedProgram.<init>(PackagedProgram.java:116)
        at org.apache.flink.client.program.PackagedProgram.<init>(PackagedProgram.java:61)
        at org.apache.flink.client.program.PackagedProgram$Builder.build(PackagedProgram.java:585)
        at com.github.hairless.plink.service.impl.LocalFlinkClusterServiceImpl.submitJob(LocalFlinkClusterServiceImpl.java:61)
        at com.github.hairless.plink.schedule.task.SubmitJobTask.asyncSubmitJobTask(SubmitJobTask.java:55)
        at com.github.hairless.plink.schedule.task.SubmitJobTask$$FastClassBySpringCGLIB$$86b74b1f.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by sllence** [comment]
这是在local模式下提交jar包运行时的报错是吧
